### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3

### ISSUE THREAD

**Issue by AngryPenguinPL** [wxGlade/wxGlade#481]
i just compiled wxGlade 1.0.1 and I get this message when i try to launch it:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 261: invalid continuation byte
free(): invalid pointer
```
OS: OpenMandriva Cooker
Python: 3.9.2
python-wxpython4: 4.1.1

Full log:
```
[x@OpenMandriva-Cooker ~]$ wxglade
Traceback (most recent call last):
  File "/usr/bin/../lib/python3.9/site-packages/wxglade/wxglade.py", line 47, in <module>
    import common, config, compat, log
  File "/usr/lib/python3.9/site-packages/wxglade/common.py", line 24, in <module>
    import config, compat, plugins, misc
  File "/usr/lib/python3.9/site-packages/wxglade/compat.py", line 25, in <module>
    import wx
  File "/usr/lib64/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/usr/lib64/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 261: invalid continuation byte
free(): invalid pointer
Aborted (core dumped)
```

Here is dump log:

```
Started wxglade.
mar 15 15:07:41 OpenMandriva-Cooker systemd[1]: Started Process Core Dump (PID 7132/UID 0).
mar 15 15:07:41 OpenMandriva-Cooker systemd-coredump[7133]: Process 7116 (python) of user 1001 dumped core.
                                                            
                                                            Stack trace of thread 7116:
                                                            #0  0x00007f5e34533397 raise (libc.so.6 + 0x40397)
                                                            #1  0x00007f5e34519538 abort (libc.so.6 + 0x26538)
                                                            #2  0x00007f5e3457a7a6 __libc_message (libc.so.6 + 0x877a6)
                                                            #3  0x00007f5e3458316c malloc_printerr (libc.so.6 + 0x9016c)
                                                            #4  0x00007f5e3458487c _int_free (libc.so.6 + 0x9187c)
                                                            #5  0x00007f5e34587fe4 __libc_free (libc.so.6 + 0x94fe4)
                                                            #6  0x00007f5e348c8a08 _PyMem_RawFree (libpython3.9.so.1.0 + 0x1f3a08)
                                                            #7  0x00007f5e348c8d4e _PyObject_Free (libpython3.9.so.1.0 + 0x1f3d4e)
                                                            #8  0x00007f5e348e793b type_dealloc (libpython3.9.so.1.0 + 0x21293b)
                                                            #9  0x00007f5e349c2315 collect (libpython3.9.so.1.0 + 0x2ed315)
                                                            #10 0x00007f5e349c1be5 collect_with_callback (libpython3.9.so.1.0 + 0x2ecbe5)
                                                            #11 0x00007f5e349c2f8a PyGC_Collect (libpython3.9.so.1.0 + 0x2edf8a)
                                                            #12 0x00007f5e3499bd45 Py_FinalizeEx (libpython3.9.so.1.0 + 0x2c6d45)
                                                            #13 0x00007f5e349bf72e Py_RunMain (libpython3.9.so.1.0 + 0x2ea72e)
                                                            #14 0x00007f5e349c08ba pymain_main (libpython3.9.so.1.0 + 0x2eb8ba)
                                                            #15 0x00007f5e349c0a82 Py_BytesMain (libpython3.9.so.1.0 + 0x2eba82)
                                                            #16 0x0000000000201884 main (python3.9 + 0x1884)
                                                            #17 0x00007f5e3451b52d __libc_start_main (libc.so.6 + 0x2852d)
                                                            #18 0x000000000020175a _start (python3.9 + 0x175a)

```

**Comment by DietmarSchwertberger** [comment]
I don't know how to interpret your report.
The message looks like a problem in wxPython.
Do Python and wxPython work for you?

**Comment by AngryPenguinPL** [comment]
Yes, looks like this is issue on my end. Thanks
